# version: '3'

# services:
#   my-regulator2:
#     build: 
#       context: .
#       dockerfile: DockerfileRegulator
#     restart: always

#   subsfront:
#     build: 
#       context: .
#       dockerfile: Dockerfile
#     restart: always
#     ports:
#       - "8000:80"
    



version: '3'
services:
   watchtower:
      image: containrrr/watchtower
      container_name: watchtower
      volumes:
         - /var/run/docker.sock:/var/run/docker.sock
      command: --schedule "* * * * *"
   solidityfront:
      image: mikethemike03/projet-devops
      container_name: solidityfront
      restart: always
      ports:
         - "8000:80"