kind: Deployment
apiVersion: apps/v1
metadata:
  name: react-docker
spec:
  replicas: 2
  selector:
    matchLabels:
      app: react-docker
  template:
    metadata:
      labels:
        app: react-docker
    spec:
      containers:
        - name: react-docker1
          image: mikethemike03/projet-devops
          ports:
            - containerPort: 80
        - name: react-docker2
          image: mikethemike03/projet-devops
          ports:
            - containerPort: 80
