apiVersion: v1
kind: Pod
metadata:
  name: my-pod
spec: 
  containers:
    - name: container-1
      image: my-image-1:latest
      ports:
        - containerPort: 80
    - name: container-2
      image: my-image-2:latest
      ports:
        - containerPort: 80