apiVersion: v1
kind: Service
metadata:
  name: service-container-1
spec:
  selector:
    app: my-app-label # Replace with the appropriate label selector for container-1
  type: NodePort
  ports:
    - protocol: TCP
      port: 80 # Expose the Service on port 80
      targetPort: 8080 # Target port for container-1
      nodePort: 30001 # Unique nodePort for container-1 (in the range 30000-32767)

---

apiVersion: v1
kind: Service
metadata:
  name: service-container-2
spec:
  selector:
    app: my-app-label # Replace with the appropriate label selector for container-2
  type: NodePort
  ports:
    - protocol: TCP
      port: 81 # Expose the Service on port 81
      targetPort: 8081 # Target port for container-2
      nodePort: 30002 # Unique nodePort for container-2 (in the range 30000-32767)
